api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('passwords', views.PasswordList.as_view(), name='password-list'),
    path('passwords/<int:pk>', views.PasswordDetail.as_view(), name='password-detail'),
    path('login', views.LoginUser.as_view(), name='login-user'),
    path('logout', views.LogoutUser.as_view(), name='logout-user'),
    path('register', views.RegisterUser.as_view(), name='register-user'),
    path('verify-master-password', views.VerifyMasterPassword.as_view(), name='verify-master-password'),
    path('update-user-data', views.UpdateUserData.as_view(), name='update-user-data')
]

frontend/urls.py
from django.urls import path
from . import views

app_name = "frontend"

urlpatterns = [
    path('', views.landing, name='landing'),
    path('vault', views.index, name='vault'),
    path('accounts', views.landing, name='accounts'),
    path('settings', views.settings, name='settings')
]

password_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-auth', include('rest_framework.urls'), name='auth'),
    path('', include('frontend.urls'))
]

api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

class Password(models.Model):
    email = models.EmailField(null=True, blank=True)
    username = models.CharField(max_length=64, null=True, blank=True)
    encrypted_password = models.CharField(max_length=256)
    url = models.URLField(max_length=256, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='passwords')
    tags = models.JSONField(null=True)

frontend/models.py
from django.db import models

# Create your models here.

api/views.py
from .models import User, Password
from .serializers import UserSerializer, PasswordSerializer
from rest_framework import generics
from .permissions import IsOwner
from rest_framework import permissions
from rest_framework.views import APIView
from django.contrib.auth import authenticate, login, logout
from rest_framework.response import Response
from django.db.models import Q
from django.contrib.auth.hashers import make_password


# Create your views here.

class PasswordList(generics.ListCreateAPIView,
                    generics.UpdateAPIView):
    queryset = Password.objects.all()
    serializer_class = PasswordSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner]

    def get(self, request):
        q = request.query_params.get('q', None)
        if q is None:
            return super().get(request)
    
        passwords = Password.objects.filter(user=request.user)
        passwords = passwords.filter(Q(url__icontains=q)
                                     |Q(email__icontains=q)
                                     |Q(username__icontains=q))
                                     #|Q(tags__tags__contains =q)) JSON filtering is not supported in SQLite
                                     # Will try to make it work when I change the database backend to PostgreSQL
        serializer = PasswordSerializer(passwords, many=True)
        return Response(serializer.data)

    def patch(self, request):
        passwords = Password.objects.filter(user=request.user)
        # serialize all passwords
        for i in range(len(passwords)):
            serializer = PasswordSerializer(passwords[i], data=request.data['passwords'][i])
            if serializer.is_valid():
                serializer.save()
            else:
                return Response({"errors": serializer.errors}, status=400)
        return Response({"msg": "Saved all passwords successfully."}, status=200)


    def get_queryset(self):
        return Password.objects.filter(user=self.request.user).order_by('url')
    
    def perform_create(self, serializer):
        return serializer.save(user=self.request.user)
    

class UpdateUserData(APIView):
    def patch(self, request):
        user = User.objects.get(username=request.user.username)
        new_username = request.data.get('new_username', None)
        password = request.data.get('password', None)
        new_password = request.data.get('new_password', None)
        if password is None:
            return Response({"error": "Master password is required."}, status=400)

        if not user.check_password(password):
            return Response({"error": "Wrong master password."}, status=400)
            
        if new_username is not None and new_username != '':
            try:
                existing_user = User.objects.get(username=new_username)
                return Response({"error": "Username already taken."}, status=400)
            except User.DoesNotExist:
                user.username = new_username

        if new_password is not None and new_password != '':
            user.set_password(new_password)

        user.save()
        login(request, user)
        return Response({"User credentials updated successfully."}, status=200)    


class PasswordDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Password.objects.all()
    serializer_class = PasswordSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner]

    


class VerifyMasterPassword(APIView):
    def post(self, request):
        return Response(request.user.check_password(request.data['master_password']))


class RegisterUser(APIView):
    def post(self, request):
        try:
            existing_user = User.objects.get(username=request.data['username'])
            return Response({"error": "Username already taken."}, status=400)
        except User.DoesNotExist:
            user = User.objects.create_user(username=request.data['username'], password=request.data['password'])
            user.save()
            login(request, user)
            return Response({"Registered successfully."}, status=200)


class LoginUser(APIView):
    def post(self, request):
        user = authenticate(request, username=request.data['username'], password=request.data['password'])
        if user is not None:
            login(request, user)
            return Response({"Logged in successfully."}, status=200)
        else:
            return Response({"Invalid credentials."}, status=400)


class LogoutUser(APIView):
    def get(self, request):
        logout(request)
        return Response({"Logged out successfully."},status=200)

frontend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse

# Create your views here.


@api_view()
def index(request):
    if request.user.is_authenticated == False:
        return redirect(reverse('frontend:landing'))
    return render(request, 'frontend/vault.html')


def settings(request):
    if request.user.is_authenticated == False:
        return redirect(reverse('frontend:landing'))
    return render(request, 'frontend/settings.html')


def landing(request):
    if request.user.is_authenticated:
        return redirect(reverse('frontend:vault'))
    return render(request, 'frontend/landing.html')

frontend/templates/frontend/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'frontend/logo.png' %}">
    <title>Vault Guard</title>
    <style>
        .curved {
            position: relative;
            background: #212529;
            height: 50vh;
            border-bottom-left-radius: 50% 0%;
            border-bottom-right-radius: 50% 0%;
        }
    </style>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'frontend:landing' %}"><img src="{% static 'frontend/logo.png' %}"
                style="height: 50px; width: 50px">Vault Guard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#login-modal" data-bs-toggle="modal"
                        data-bs-target="#login-modal">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#register-modal" data-bs-toggle="modal"
                        data-bs-target="#register-modal">Register</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- Login Modal -->
<div class="modal fade" id="login-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="w-75 mx-auto mb-4" id="login-form">
                    <input class="form-control mb-2" type="text" name="username" id="login-username"
                        placeholder="Username">
                    <input class="form-control mb-2" type="password" name="password" id="login-password"
                        placeholder="Password">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark w-100" id="login-button">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Register Modal -->
<div class="modal fade" id="register-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Register</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="w-75 mx-auto" id="register-form">
                    <input class="form-control mb-2" type="text" name="username" id="register-username"
                        placeholder="Username">
                    <input class="form-control mb-2" type="password" name="password" id="register-password"
                        placeholder="Password">
                    <input class="form-control mb-2" type="password" name="password_" id="register-password_"
                        placeholder="Re-enter password">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark w-100" id="register-button">Register</button>
                </form>
            </div>
        </div>
    </div>
</div>

<body class="text-center">
    <section class="curved mb-5">
        <img src="{% static 'frontend/logo.png' %}">
        <h1 class="mb-4" style="color:rgb(255, 255, 255)">Vault Guard</h1>
        <p style="color:rgb(255, 255, 255)">A secure open-source password manager for everyone.</p>
    </section>
    <h1>Why choose Vault Guard?</h1>
    <div class="container">
        <div class="row justify-content-center p-5">
            <div class="card col-12 col-md-6 m-5 border-0" style="width: 18rem;">
                <img src="{% static 'frontend/home-security-icon.png' %}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Trusted Security</h5>
                    <p class="card-text">Your private information is protected with end-to-end encryption before it ever
                        leaves your device.</p>
                </div>
            </div>
            <div class="card col-12 col-md-6 m-5 border-0" style="width: 18rem;">
                <img src="{% static 'frontend/home-open-source-icon.png' %}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Open Source Transparency</h5>
                    <p class="card-text">Vault Guard source code, features, and infrastructure security are open source.
                    </p>
                </div>
            </div>

        </div>
    </div>

    <footer>
        <a href="http://github.com/adhamsalama/password_manager">Source code.</a>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="{% static 'frontend/postData.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/getCookie.js' %}" type="text/javascript"></script>

    <script>
        document.querySelector("#login-form").onsubmit = () => false;
        let loginButton = document.querySelector("#login-button");
        loginButton.onclick = () => {
            let username = document.querySelector("#login-username").value;
            let password = document.querySelector("#login-password").value;
            postData(`${window.location.origin}/api/login`, data = {
                username: username,
                password: password
            })
                .then(response => {
                    if (response.ok)
                        window.location.replace(`${window.location.origin}/vault`);
                    else {
                        alert("Invalid credentials.");
                    }
                })
        }
        document.querySelector("#register-form").onclick = () => false;
        let registerButton = document.querySelector("#register-button");
        registerButton.onclick = () => {
            let username = document.querySelector("#register-username").value;
            let password = document.querySelector("#register-password").value;
            let password_ = document.querySelector("#register-password_").value;
            if (password !== password_) {
                alert("Passwords don't match");
                return;
            }
            postData(`${window.location.origin}/api/register`, data = {
                username: username,
                password: password
            })
                .then(response => {
                    if (response.ok) {
                        alert("Registered!");
                        window.location.replace(`${window.location.origin}/vault`);
                    }
                    else
                        response.json().then(result => alert(result.error));
                });
        }

    </script>
</body>

</html>

frontend/templates/frontend/layout.html
{% load static %}

<html>

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %}</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'frontend/logo.png' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="{% static 'frontend/styles.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body class="">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'frontend:vault' %}"><img src="{% static 'frontend/logo.png' %}" style="height: 50px; width: 50px">Vault Guard</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'frontend:vault' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'frontend:settings' %}">Settings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#" aria-current="page" id="logout-button">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container p-4">
{% block body %}

{% endblock body %}
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script>
    
        {% block script %}{% endblock script %}
    
    </body>
</html>

frontend/templates/frontend/settings.html
{% extends 'frontend/layout.html' %}
{% load static %}
{% block title %}Settings{% endblock title %}
{% block body %}
    <h1 class="w-75 mx-auto">Settings</h1>
    <form id="change-mpw-form" class="w-75 mx-auto">
        <input type="text" name="new-username" id="new-username" class="form-control mb-2" placeholder="New username">
        <input type="password" name="old-mpw" id="old-mpw" class="form-control mb-2" placeholder="Master Password">
        <input type="password" name="new-mpw" id="new-mpw" class="form-control mb-2" placeholder="New Master Password">
        <input type="password" name="confirm-new-mpw" id="confirm-new-mpw" class="form-control mb-2" placeholder="Re-enter Master Password">
        <div class="d-grid">
            <button class="btn btn-primary" type="submit">Update</button>
        </div>
    </form>
    {% endblock body %}
{% block script %}

<script src="{% static 'frontend/getPasswords.js' %}" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script>
    <script src="{% static 'frontend/crypto.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/patchData.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/getCookie.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/verifyMasterPassword.js' %}" type="text/javascript"></script>    
    <script src="{% static 'frontend/postData.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/logout.js' %}" type="text/javascript"></script>
    <script>
        document.querySelector("#change-mpw-form").onsubmit = () => {
            let masterPassword = document.querySelector("#old-mpw").value;
            let newMasterPassword = document.querySelector("#new-mpw").value;
            let newUsername = document.querySelector("#new-username").value; 
            patchData(`${window.location.origin}/api/update-user-data`, data={
                new_username: newUsername,
                password: masterPassword,
                new_password: newMasterPassword
            })
            .then(response  => {
                // couldn't update user data
                if(!response.ok) {
                    response.json().then(result => alert(result.error))
                    return false;
                }
                // could update user data with new username, but no new master password was given
                // so don't need to re-encrypt all passwords
                if(newMasterPassword == "") {
                    alert("User data updated successfully.")
                    return false;
                }
                // updated username and master password
                // re-encrypt all passwords and send the vault to the server
                getPasswords()
                .then(passwords => {
                    console.log(passwords);
                    passwords.forEach(password => {
                        // reencrypt passwords
                        let plaintext = decrypt(password.encrypted_password, masterPassword)
                        let newEncryptedPassword = encrypt(plaintext, newMasterPassword);
                        password.encrypted_password = newEncryptedPassword;
                    })
                    // send encrypted passwords
                    patchData(`${window.location.origin}/api/passwords`, data={passwords: passwords})
                    .then(response => response.json())
                    .then(result => {
                        alert("User data updated and passwords re-encrypted successfully.");
                    })
                });
            })
                
            
            return false;
        }
    </script>
{% endblock script %}

frontend/templates/frontend/vault.html
{% extends 'frontend/layout.html' %}

{% load static %}
{% block title %}Vault{% endblock title %}
{% block body %}

        <div class="row mx-auto">
          <!--Add password form-->
          <form id="add-password-form" class="col-12 col-sm-12 col-md-6" method="post" action="http://127.0.0.1:8000/api/passwords">
              <input class="form-control mb-2" autofocus  type="text" id="email" name="email" placeholder="Email">
              <input class="form-control mb-2"  type="text" id="username" name="username" placeholder="Username">
              <input class="form-control mb-2"  type="password" id="password" name="password" placeholder="Password">
              <input class="form-control mb-2"  type="text" id="url" name="url" placeholder="URL">
              <input class="form-control mb-2"  type="text" id="tags" name="tags" placeholder="Tags">
              <div class="d-grid">
                <button class="btn btn-primary" id="add-button">Add</button>
              </div>
          </form>
          <!--Random Password Generator-->
          <div class="card mx-auto text-center col-12 col-sm-12 col-md-6">
            <h5 class="card-header">Random Password Generator</h5>
            <div class="card-body">
                <input type="number" id="length" class="form-control mb-2" placeholder="Length">
                <div class="d-grid">
                  <button class="btn btn-primary mb-2" id="generate-password">Generate</button>
                  <button class="btn btn-primary mb-2" id="copy-generated-password">Copy</button>
                </div>
                <div id="generated-password" class="mt-4"></div>
            </div>
          </div>
        </div>
        
        
        <form id="search-form">
            <div class="mb-3 mx-auto">
                <label for="q" class="form-label">Search</label>
                <input type="text" class="form-control" id="q">
            </div>
        </form>
        <div id="passwords" class="accordion mx-auto"></div>
        <div class="modal" id="modal" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <input class="form-control" type="password" id="master-password-input">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="encrypt-decrypt-button" data-bs-dismiss="modal">Confirm</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
<div class="modal" id="edit-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Password</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <input type="text" class="edit-email form-control mb-2">
        <input type="text" class="edit-username form-control mb-2">
        <input type="password" class="edit-password form-control mb-2" placeholder="Enter new password">
        <input type="password" class="edit-master-password form-control mb-2" placeholder="Enter master password">
        <input type="text" class="edit-url form-control mb-2" placeholder"URL">
        <input type="text" class="edit-tags form-control mb-2" placeholder="Tags">
      </div>
      <div class="modal-footer">
        <button type="button" id="edit-modal-save" class="btn btn-primary" data-bs-dismiss="modal">Save changes</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock body %}
{% block script %}
    <script src="{% static 'frontend/crypto.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/getPasswords.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/displayPasswords.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/getCookie.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/addPassword.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/logout.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/postData.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/patchData.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/decryptAndCopyPassword.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/getMasterPassword.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/searchPasswords.js' %}" type="text/javascript"></script>    
    <script src="{% static 'frontend/verifyMasterPassword.js' %}" type="text/javascript"></script>    
    <script src="{% static 'frontend/modalClose.js' %}" type="text/javascript"></script>    
    <script src="{% static 'frontend/modalAddPassword.js' %}" type="text/javascript"></script>    
    <script src="{% static 'frontend/editPasswordEvent.js' %}" type="text/javascript"></script>    
    <script src="{% static 'frontend/deletePasswordEvent.js' %}" type="text/javascript"></script>
    <script src="{% static 'frontend/random.js' %}" type="text/javascript"></script>    
    <script> 
        getPasswords()
        .then(results => displayPasswords(results));

        function HtmlEncode(s) {
          // function to espace HTML special characters
          let el = document.createElement("div");
          el.innerText = el.textContent = s;
          s = el.innerHTML;
          return s;
      }
        // Generate random password
        document.querySelector("#generate-password").onclick = () => {
            let length = parseInt(document.querySelector("#length").value);
            let generatedPassword = generateRandomPassword(length);
            document.querySelector("#generated-password").innerHTML = HtmlEncode(generatedPassword); //HtmlEncode(generatedPassword);
        }

        // Copy generated random password
        document.querySelector("#copy-generated-password").onclick = () => navigator.clipboard.writeText(document.querySelector("#generated-password").innerText.trim());
    </script>

{% endblock script %}